[tool.pyright]
typeCheckingMode = "strict"
reportIncompatibleMethodOverride = false

[tool.ruff]
line-length = 88
select = ["ALL"]
ignore = ["D", "ANN", "COM", "A003", "TD001", "TD002", "S108", "I001", "F403", "A002", "SLF001", "T201", "F841", "E402", "PLR0913", "S603", "S607", "S101", "A001", "EM101", "TRY003", "EM102", "E721", "FBT003", "S324"]

[tool.isort]
skip_gitignore = true
line_length = 128
length_sort = true
# string annotations allow using things not defined yet.
add_imports = ["from __future__ import annotations"]
force_single_line = true
atomic = true
# makes import statements tight.
lines_between_sections = 0
